name: Update Age

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 8 11 *'

jobs:
  update-age:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./scripts

      - name: Set execute permissions
        run: chmod +x node_modules/.bin/ts-node
        working-directory: ./scripts

      - name: Run age update script
        run: npx ts-node updateAge.ts
        working-directory: ./scripts

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push if changed
        run: |
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update age in README"
            git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
          fi
